%Agent(AgentName,AgentType,freq,nec,cap).
Agent(agp1,agp,0,1000,0).
Agent(agw1,agw,0,1000,0).
Agent(agq1,agq,0,1000,0).
Agent(agw2,agw,0,1000,0).
Agent(agw3,agw,0,1000,0).
%Station(StationName,StattionType,freq,nec,space).
Station(stb1,stb,0,1,0).
Station(stc1,stc,0,1,0).
Station(stm1,stm,0,1000,0).
Station(stp1,stp,0,1,0).
Station(sta1,sta,0,1,0).
Station(stq1,stq,0,1,0).
%VisitEdge(agentName,AgentTypeName,StationName,StationTypeName,bold).
VisitEdge(agp1,agp,sta1,sta,false).
VisitEdge(agw1,agw,stp1,stp,false).
VisitEdge(agw3,agw,stp1,stp,false).
VisitEdge(agq1,agq,sta1,sta,false).
VisitEdge(agw2,agw,stp1,stp,false).
VisitEdge(agq1,agq,stc1,stc,false).
VisitEdge(agw1,agw,stq1,stq,false).
VisitEdge(agp1,agp,stc1,stc,false).
VisitEdge(agp1,agp,stb1,stb,false).
VisitEdge(agq1,agq,stb1,stb,false).
VisitEdge(agw1,agw,stm1,stm,false).
VisitEdge(agw2,agw,stm1,stm,false).
VisitEdge(agw3,agw,stq1,stq,false).
VisitEdge(agw2,agw,stq1,stq,false).
VisitEdge(agw3,agw,stm1,stm,false).
%NecAgentStation(AgentName,StationName,Nec).
NecAgentStation(agq1,stb1,0). 
NecAgentStation(agq1,sta1,0). 
NecAgentStation(agw1,stq1,0). 
NecAgentStation(agw2,stq1,0). 
NecAgentStation(agw1,stp1,0). 
NecAgentStation(agw2,stm1,0). 
NecAgentStation(agp1,stc1,0). 
NecAgentStation(agw3,stq1,0). 
NecAgentStation(agp1,sta1,0). 
NecAgentStation(agw2,stp1,0). 
NecAgentStation(agw3,stm1,0). 
NecAgentStation(agw3,stp1,0). 
NecAgentStation(agw1,stm1,0). 
NecAgentStation(agq1,stc1,0). 
NecAgentStation(agp1,stb1,0). 
%ItemSetLoadingAgent(AgentName,StationTypeName,ItemNumber).
%ItemSetLoadingStation(StationTypeNameIn,StationNameOut,ItemNumber).
%TimeEdgeStatus(NameWithTimeEdge,TypeNameWithTimeEdge,NameVisited,TypeNameVisited,EdgeType,EchTime,Type,CountTick,IsWaiting,IsReady,IsFinish).
TimeEdgeState(stm1,stm,agw2,agw,0,true,0,0,false,false,false).
TimeEdgeState(stq1,stq,agw3,agw,1,false,0,0,false,false,false).
TimeEdgeState(agp1,agp,sta1,sta,1,false,1,0,false,false,false).
TimeEdgeState(stm1,stm,agw3,agw,0,true,0,0,false,false,false).
TimeEdgeState(stc1,stc,agq1,agq,0,true,0,0,false,false,false).
TimeEdgeState(agq1,agq,sta1,sta,1,false,1,0,false,false,false).
TimeEdgeState(stq1,stq,agw2,agw,1,false,0,0,false,false,false).
TimeEdgeState(stm1,stm,agw1,agw,0,true,0,0,false,false,false).
TimeEdgeState(agp1,agp,stc1,stc,1,false,1,0,false,false,false).
TimeEdgeState(stp1,stp,agw3,agw,1,false,0,0,false,false,false).
TimeEdgeState(agq1,agq,stc1,stc,1,false,1,0,false,false,false).
TimeEdgeState(agp1,agp,stb1,stb,1,false,1,0,false,false,false).
TimeEdgeState(stp1,stp,agw2,agw,1,false,0,0,false,false,false).
TimeEdgeState(stp1,stp,agw1,agw,1,false,0,0,false,false,false).
TimeEdgeState(stc1,stc,agp1,agp,0,true,0,0,false,false,false).
TimeEdgeState(stq1,stq,agw1,agw,1,false,0,0,false,false,false).
TimeEdgeState(agq1,agq,stb1,stb,1,false,1,0,false,false,false).
% CurrentAgent(AgentName,AgentTypeName). 
CurrentAgent(agp1,agp).
% CurrentStation(AgentName,AgetnTypeName,StationName,StationTypeName,IsInStation,HasChoose). 
CurrentStation(agp1,agp,nothings,nothings,false,false).
