ZeitEinheit(1).
%AgentType(AgentTypeName,freq,nec,time,prio,cycle,cap,size,speed).
AgentType(course,1000,1000,1,1,0,1000,1,1).
AgentType(class,1000,1000,1,1,0,1000,1,1).
%StationType(StationTypeName,freq,nec,time,prio,cylce,item,space,count)
StationType(literature,1000,1,1,1,0,0,1,3).
StationType(room,1000,1000,1,1,0,0,1,4).
StationType(mathematics,1000,1,1,1,0,0,1,2).
%PlacedEdge(StationNameIn,StationTypeNameIn,StationNameOut,StationTypeNameOut,Weight,directed).
PlacedEdge(mathematics2,mathematics,literature2,literature,0,false).
PlacedEdge(mathematics2,mathematics,literature3,literature,0,false).
PlacedEdge(mathematics2,mathematics,literature1,literature,0,false).
PlacedEdge(mathematics1,mathematics,literature1,literature,0,false).
PlacedEdge(mathematics1,mathematics,literature2,literature,0,false).
PlacedEdge(mathematics1,mathematics,literature3,literature,0,false).
%TimeEdge(Name1,TypeName1,Name2,TypeName2,TimeType,IsDirected,ConnectionType,weight).
TimeEdge(mathematics2,mathematics,course1,course,2,false,false,0).
TimeEdge(literature2,literature,course2,course,2,false,false,0).
TimeEdge(mathematics1,mathematics,course2,course,2,false,false,0).
TimeEdge(literature1,literature,course1,course,2,false,false,0).
TimeEdge(literature1,literature,course3,course,2,false,false,0).
TimeEdge(literature3,literature,course4,course,2,false,false,0).
TimeEdge(literature2,literature,course5,course,2,false,false,0).
TimeEdge(mathematics1,mathematics,course3,course,2,false,false,0).
TimeEdge(literature3,literature,course2,course,2,false,false,0).
TimeEdge(literature1,literature,course5,course,2,false,false,0).
TimeEdge(literature2,literature,course4,course,2,false,false,0).
TimeEdge(literature2,literature,course3,course,2,false,false,0).
TimeEdge(mathematics2,mathematics,course5,course,2,false,false,0).
TimeEdge(literature1,literature,course4,course,2,false,false,0).
TimeEdge(literature3,literature,course3,course,2,false,false,0).
TimeEdge(mathematics1,mathematics,course1,course,2,false,false,0).
TimeEdge(mathematics2,mathematics,course2,course,2,false,false,0).
TimeEdge(literature1,literature,course2,course,2,false,false,0).
TimeEdge(mathematics1,mathematics,course5,course,2,false,false,0).
TimeEdge(mathematics1,mathematics,course4,course,2,false,false,0).
TimeEdge(mathematics2,mathematics,course3,course,2,false,false,0).
TimeEdge(mathematics2,mathematics,course4,course,2,false,false,0).
TimeEdge(literature2,literature,course1,course,2,false,false,0).
TimeEdge(literature3,literature,course1,course,2,false,false,0).
TimeEdge(literature3,literature,course5,course,2,false,false,0).
